import { ScrollArea, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";

const font = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Theme
          appearance="dark"
          accentColor="crimson"
          grayColor="mauve"
          panelBackground="solid"
          radius="large"
        >
          <div className=" flex min-h-[100dvh] flex-col">
            <header className=" sticky top-0 h-16 flex-none border-b border-[#3a363c] bg-[#191719]"></header>
            <div className=" flex flex-grow">
              <aside className=" sticky top-16 hidden h-[calc(100dvh_-_8rem)] w-80  border-b border-[#3a363c]  md:block">
                <ScrollArea>{children}</ScrollArea>
              </aside>
              <main className=" flex-grow border-b border-[#3a363c] md:border-l ">
                {children}
              </main>
            </div>
            <footer className=" h-16 flex-none"></footer>
          </div>
        </Theme>
      </body>
    </html>
  );
}
